# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user1 = User.create(username: "hjyam", password: "password");

class1 = ClassName.create(name: "KHAS 1")
class2 = ClassName.create(name: "KHAS 2")
class3 = ClassName.create(name: "KHAS 3")
class4 = ClassName.create(name: "KHAS 4")
class5 = ClassName.create(name: "1B")
class6 = ClassName.create(name: "2B")
class7 = ClassName.create(name: "3B")
class8 = ClassName.create(name: "4B")
class9 = ClassName.create(name: "5B")
class10 = ClassName.create(name: "6B")
class11 = ClassName.create(name: "1C")
class12= ClassName.create(name: "2C")
class13 = ClassName.create(name: "3C")
class14 = ClassName.create(name: "4C")
class15 = ClassName.create(name: "5C")
class16 = ClassName.create(name: "6C")
class17 = ClassName.create(name: "2E")
class18 = ClassName.create(name: "3E")
class19 = ClassName.create(name: "4E")
class20 = ClassName.create(name: "1H")
class21 = ClassName.create(name: "2H")
class22 = ClassName.create(name: "3H")
class23 = ClassName.create(name: "4H")
class24 = ClassName.create(name: "5H")
class25 = ClassName.create(name: "6H")
class26 = ClassName.create(name: "1J")
class27 = ClassName.create(name: "2J")
class28 = ClassName.create(name: "3J")
class29 = ClassName.create(name: "4J")
class30 = ClassName.create(name: "5J")
class31 = ClassName.create(name: "6J")
class32 = ClassName.create(name: "1K")
class33 = ClassName.create(name: "2K")
class34 = ClassName.create(name: "3K")
class35 = ClassName.create(name: "4K")
class36 = ClassName.create(name: "5K")
class37 = ClassName.create(name: "6K")
class38 = ClassName.create(name: "1M")
class39 = ClassName.create(name: "2M")
class40 = ClassName.create(name: "3M")
class41 = ClassName.create(name: "4M")
class42 = ClassName.create(name: "5M")
class43 = ClassName.create(name: "6M")
class44 = ClassName.create(name: "1P")
class45 = ClassName.create(name: "2P")
class46 = ClassName.create(name: "3P")
class47 = ClassName.create(name: "4P")
class48 = ClassName.create(name: "5P")
class49 = ClassName.create(name: "6P")
class50 = ClassName.create(name: "1U")
class51 = ClassName.create(name: "2U")
class52 = ClassName.create(name: "3U")
class53 = ClassName.create(name: "4U")
class54 = ClassName.create(name: "5U")
class55 = ClassName.create(name: "6U")

student1 = Student.create(name: "huijun", lateness: 0, class_id: class1.id)
student2 = Student.create(name: "huixuan", lateness: 0, class_id: class1.id)
student3 = Student.create(name: "seiktee", lateness: 0, class_id: class2.id)
student4 = Student.create(name: "kokhong", lateness: 0, class_id: class1.id)
student5 = Student.create(name: "alice", lateness: 0, class_id: class2.id)
